### ISSUE TITLE
New a2s_ requests

### ISSUE THREAD

**Issue by Pok4** [tltneon/lgsl#102]
I see that gameq was updated about new requests via A2S_ source engine protocol... When i tested the class i get some servers (css/csgo/cs1.6) offline, some are online. (i tested alot servers from gt.com/gt.rs).. And i'm wondering about your game query protocol, it was updated for this new A2S_ (S*hit) ?

I know about the emulators (revemu, dproto and rehlds for cs 1.6), maybe steam (valve) is trying to stop use of this things and they update the engine...

Can you tell me more about your querying class and will works with this games without problem ?

**Comment by tltneon** [comment]
LGSL [source query protocol](https://github.com/tltneon/lgsl/blob/master/lgsl_files/lgsl_protocol.php#L1103) was updated to new A2S_ about 6 months ago #60 because of servers starts send challenge number https://developer.valvesoftware.com/wiki/Server_queries#A2S_INFO

I'm not sure is LGSL can works properly with emulators - we need some examples to improve query protocol

**Comment by Pok4** [comment]
Ok, tomorrow i will test with a lot of servers.  I know a site with servers using emulators - https://amxx-bg.info/servers/
The bulgarian servers is based on rehlds. (a lot of)

I will test and if i get a server with status offline and the server is online i will repot the ips here...

Thank you for your reply and time :)
