### ISSUE TITLE
Query for CryoFall

### ISSUE THREAD

**Issue by BaxAndrei** [tltneon/lgsl#109]
Hi. Would it be possible to add query for CryoFall? Thank you.

**Comment by tltneon** [comment]
Hi, @BaxAndrei 

Okay, I will try. I need at least one IP of working server.
Do you have any tech docs (as you added for PZ)? It could help.

**Comment by BaxAndrei** [comment]
I hope this help: https://wiki.atomictorch.com/CryoFall/Server/Setup

**Comment by tltneon** [comment]
Hi, @BaxAndrei 

So, since last year I found no any docs or scripts that can help with querying...
I made script that simulates connecting to server and try getting some server's info. It works well on version 1.33.1. Unfortunately, it could be broke when new updates is coming.
![image](https://github.com/tltneon/lgsl/assets/2452201/97c216e2-f95a-4b2e-82ca-40113d188f8e)
 
![image](https://github.com/tltneon/lgsl/assets/2452201/236df9f3-06d9-454e-85ae-bc5fb5d9d7bf)

**Comment by BaxAndrei-SEC-ACC** [comment]
Is this added to gitlab so I can use IT @tltneon ?

**Comment by tltneon** [comment]
Yep 👌

**Comment by BaxAndrei** [comment]
> Yep 👌
@tltneon 

I installed latest commit but I cant find it to select from the list :( 
![image](https://github.com/tltneon/lgsl/assets/12484505/e9c396c5-941c-4091-b307-39811ab75d90)

**Comment by tltneon** [comment]
I forgot to mention that I added it to https://github.com/tltneon/lgsl/tree/lgsl7 branch. If you need I can add that protocol to master branch

**Comment by BaxAndrei** [comment]
Thank you! I forked it!

**Comment by BaxAndrei** [comment]
@tltneon I found game source code: https://github.com/AtomicTorchStudio/CryoFall . They made it public, maybe this help you more with server query
