### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by fearts** [tltneon/lgsl#3]
I have a old version of this with a custom style I use for my website:

https://disc-ff.com/LiveGameServerList/lgsl/

If I gave you the files would it be possible to add this custom style to your version? My version is having errors with PHP 7+ and will soon no longer work when my hosts updates.

Warning: Use of undefined constant MYSQL_ASSOC - assumed 'MYSQL_ASSOC' (this will throw an Error in a future version of PHP) in /usr/www/disc/public/forums/LiveGameServerList/lgsl/lgsl_files/lgsl_class.php on line 162

Warning: Use of undefined constant MYSQL_ASSOC - assumed 'MYSQL_ASSOC' (this will throw an Error in a future version of PHP) in /usr/www/disc/public/forums/LiveGameServerList/lgsl/lgsl_files/lgsl_class.php on line 340

^It was printing these errors. So having switching to this one would be Ideal but the style you have for your I don't think looks as clean as my current one. I could pay some money also.

**Comment by tltneon** [comment]
You can replace original files (don't forget to backup old ones!) and it should be working (also don't forget to set up your configs). And yeah, I can make new style which will be look like your.

**Comment by tltneon** [comment]
@fearts , looks like you have customized LGSL because your list show not full server name as it is. So I made something similar to your style without any php code editing (working on current LGSL)
Style here: https://pastebin.com/4mgQ1zyT
![54uyty5](https://user-images.githubusercontent.com/2452201/69346355-aebb9700-0c83-11ea-9e01-0891baa6d8b6.png)
